Month7/stap 1
bronik04/react-burger pull request #1
Opened 2022-10-04 13:20 UTC by bronik04

Пока в проекте реализована только верстка.
Буду раз любым замечаниям!

2022-10-04 15:23 UTC, andryxxa93 requested changes
Хорошая работа! Проект соответствует макету. Код написан чисто и аккуратно. 

Обратите внимание на замечания, которые необходимо исправить:

1) Все компоненты которые принимают пропсы должны иметь типизацию через propTypes.
2) Названия React компонентов должны начинаться с заглавной буквы.
3) Внешний вид скролла (цвет) немного отличается. Вот как должен выглядеть.
![Снимок экрана 2022-10-04 в 18 22 27](https://user-images.githubusercontent.com/60173362/193859908-0b9c681c-2317-4bd9-bda2-31657183bd17.png)

Вы можете не исправлять эти замечания сейчас, но на финальном этапе они станут обязательны.

Удачных правок!

2022-10-04 15:23 UTC, andryxxa93 commented on src/components/burger-constructor/burger-constructor.jsx
> +const burgerConstructor = () => {
**Необходимо исправить**
Имя компонента должно начинаться с заглавной буквы

2022-10-04 15:23 UTC, andryxxa93 commented on src/components/header-button/header-button.jsx
> +export default HeaderButton;
**Необходимо исправить**
Необходимо добавить типизацию через propTypes для всех компонентов, которые принимают пропсы

2022-10-04 17:16 UTC, bronik04 commented on src/components/burger-constructor/burger-constructor.jsx
> +const burgerConstructor = () => {
Готово!

2022-10-04 17:36 UTC, bronik04 commented on src/components/header-button/header-button.jsx
> +export default HeaderButton;
Готово

2022-10-04 17:37 UTC, bronik04 commented
Сделал правки. Спасибо!

2022-10-10 13:46 UTC, andryxxa93 commented
Хорошая работа! Может приступать к финальному этапу работы.
Удачи!

2022-10-10 14:59 UTC, bronik04 commented
@andryxxa93 Привет, может я что-то сделал не так, но мне казалось что я отправлял на ревью вторую ветку с финальной версией?

2022-10-11 19:43 UTC, merged