Month7/stap 2
bronik04/react-burger pull request #2
Opened 2022-10-10 08:40 UTC by bronik04

Здравствуйте, проверьте, пожалуйста, вторую часть работы! Буду рад любым замечаниям которые смогут улучшить проект и мой код!

2022-10-10 19:04 UTC, andryxxa93 requested changes
Проделана большая работа! Вы хорошо разобрались с функциональными компонентами, правильно используете useEffect и PropTypes.

Однако есть пару моментов, которые необходимо исправить, чтобы работа была принята.

Необходимо исправить:
- Добавьте проверку успешности запроса.
- Перенесите функции закрытия модального окна внутрь компонента Modal.
-  Уберите у ModalOverlay `children`.

Более подробно описание проблемы смотрите комментарии в pull request.

Что понравилось:
- Есть отписка от слушателя.
- Есть автоскролл по категориям.
- Чистый и понятный код.

В pull request вы так же найдете комментарии с рекомендациями как **можно улучшить** код. Их делать не обязательно, однако в будущем они могут помочь избежать ошибок и сделать код лучше.

Удачных правок!

2022-10-10 19:04 UTC, andryxxa93 commented on src/App.jsx
> +    fetch(url)
**Надо исправить**
Добавьте проверку ответа сервера - res.ok:

Например:

```
.then(res => res.ok ? res.json() : res.json().then((err) => Promise.reject(err));
```

иначе сейчас, если сервер ответи не кодом 2xx, а какой либо ошибкой (4xx, 5xx) мы не попадем в catch т.к. в этом случае fetch не выбрасывает ошибку, мы попытаемся отрисовать данные, хотя они не пришли, в итоге на попытке отрисовки несуществующих данных упадет все приложение

[https://learn.javascript.ru/fetch](https://learn.javascript.ru/fetch)

[https://developer.mozilla.org/en-US/docs/Web/API/Response/ok](https://developer.mozilla.org/en-US/docs/Web/API/Response/ok)

Т.к. эта проверка нужна у всех запросов, лучше вынести её в отдельную функцию

```
const checkReponse = (res) => {
  return res.ok ? res.json() : res.json().then((err) => Promise.reject(err));
};
```

`fetch(someUrl).then(checkReponse)`

2022-10-10 19:04 UTC, andryxxa93 commented on src/App.jsx
> +    fetch(url)
**Можно лучше**

в дальнейшем добавятся ещё запросы к бэкенду и лучше вынести описание этих запросов в функции

Например:

```
function getIngredients() {
   return fetch(`${NORMA_API}/ingredients`)
    .then(проверка ответа)
}

```

и разместить их в отдельном файле  `utils/burger-api.js`, а не описывать запросы в самом компоненте

2022-10-10 19:04 UTC, andryxxa93 commented on src/App.jsx
> +        alert('Ошибка при получении данных');
**Можно улучшить**
Console.log нужен только для процесса разработки, перед сдачей проекта его нужно удалять, иначе она будет загружать консоль ненужной, а возможно и приватной информацией. А ошибку лучше записывать в state и показывать пользователю в модальном окне (которое вы уже создали), чтобы он понимал, что происходит. `Alert` лучше не использовать, у него нельзя изменить стили и он блокирует взаимодействие с сайтом.

2022-10-10 19:04 UTC, andryxxa93 commented on src/components/burger-constructor/burger-constructor.jsx
> +  };
**Необходимо исправить**
Функция закрытия по клавише ESC одинаковая для всех случаев использования модального окна. Поэтому лучше перенести внутрь модального окна. При том компоненту конструктора нет необходимости знать как закрывается модальное окно, это "вне его компетенции".

2022-10-10 19:04 UTC, andryxxa93 commented on src/components/burger-ingredients/burger-ingredients.jsx
> +  useEffect(() => {
**Отлично**
Вы реализовали автоскрол, супер, это очень удобно)

2022-10-10 19:04 UTC, andryxxa93 commented on src/components/modal-overlay/modal-overlay.jsx
> +    <div className={styles.overlay} onClick={onClick}>
**Надо исправить**

у ModalOverlay не должно быть children, это просто компонент подложки а не контейнер`

2022-10-10 19:04 UTC, andryxxa93 commented on src/components/modal/modal.jsx
> +      document.removeEventListener('keydown', onEscKeydown);
**Отлично!**
Вы сделали отписку от слушателя, это позволит избежать утечек памяти.

2022-10-11 06:43 UTC, bronik04 commented on src/components/modal-overlay/modal-overlay.jsx
> +    <div className={styles.overlay} onClick={onClick}>
Готово!

2022-10-11 07:39 UTC, bronik04 commented on src/App.jsx
> +    fetch(url)
Совет супер! Спасибо!

2022-10-11 12:31 UTC, bronik04 commented on src/App.jsx
> +    fetch(url)
Готово

2022-10-11 13:18 UTC, bronik04 commented on src/components/burger-constructor/burger-constructor.jsx
> +  };
Готово! Так действительно лучше!

2022-10-11 15:57 UTC, bronik04 commented on src/App.jsx
> +        alert('Ошибка при получении данных');
Сделано!

2022-10-11 18:43 UTC, andryxxa93 approved these changes
Отличная работа! Удачного продолжения обучения!

2022-10-11 19:43 UTC, merged